mule:
    image: marcelocorreia/mule:3.7.0 # https://registry.hub.docker.com/_/jenkins/
    ports:
     - 8081:8081
    hostname: local
    volumes:
      - /tmp/mule-apps:/usr/local/mule-standalone-3.7.0/apps
